# Generated by Django 4.2.23 on 2025-07-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='aythor',
            new_name='author',
        ),
    ]
